package com.weather3d;

import lombok.Getter;

public enum WeatherForecast {
    SPRING_ARCTIC(Condition.SEASON_SPRING, Condition.BIOME_ARCTIC, new Condition[]
            {Condition.WEATHER_CLOUDY, Condition.WEATHER_SNOWING, Condition.WEATHER_SNOWING, Condition.WEATHER_CLOUDY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_FOGGY, Condition.WEATHER_SNOWING, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_FOGGY, Condition.WEATHER_CLOUDY}),
    SPRING_BARRENS(Condition.SEASON_SPRING, Condition.BIOME_BARRENS, new Condition[]
            {Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_CLOUDY, Condition.WEATHER_RAINING, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_STORM, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY,  Condition.WEATHER_PARTLY_CLOUDY}),
    SPRING_CAVE(Condition.SEASON_SPRING, Condition.BIOME_CAVE, new Condition[]
            {Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED}),
    SPRING_COSMOS(Condition.SEASON_SPRING, Condition.BIOME_COSMOS, new Condition[]
            {Condition.WEATHER_COSMOS, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_COSMOS, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY}),
    SPRING_DESERT(Condition.SEASON_SPRING, Condition.BIOME_DESERT, new Condition[]
            {Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_RAINING, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY}),
    SPRING_FOREST(Condition.SEASON_SPRING, Condition.BIOME_FOREST, new Condition[]
            {Condition.WEATHER_SUNNY, Condition.WEATHER_FOGGY, Condition.WEATHER_RAINING, Condition.WEATHER_RAINING, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_RAINING, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_CLOUDY, Condition.WEATHER_RAINING, Condition.WEATHER_STORM, Condition.WEATHER_CLOUDY}),
    SPRING_GRASSLAND(Condition.SEASON_SPRING, Condition.BIOME_GRASSLAND, new Condition[]
            {Condition.WEATHER_RAINING, Condition.WEATHER_STORM, Condition.WEATHER_SUNNY, Condition.WEATHER_CLOUDY, Condition.WEATHER_FOGGY, Condition.WEATHER_SUNNY, Condition.WEATHER_RAINING, Condition.WEATHER_CLOUDY, Condition.WEATHER_RAINING, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_FOGGY, Condition.WEATHER_SUNNY}),
    SPRING_LAVA_CAVE(Condition.SEASON_SPRING, Condition.BIOME_LAVA_CAVE, new Condition[]
            {Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED}),
    SPRING_MOUNTAIN(Condition.SEASON_SPRING, Condition.BIOME_MOUNTAIN, new Condition[]
            {Condition.WEATHER_STORM, Condition.WEATHER_SNOWING, Condition.WEATHER_CLOUDY, Condition.WEATHER_SNOWING, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_FOGGY, Condition.WEATHER_CLOUDY, Condition.WEATHER_SNOWING, Condition.WEATHER_SNOWING, Condition.WEATHER_STORM, Condition.WEATHER_SUNNY, Condition.WEATHER_CLOUDY}),
    SPRING_SWAMP(Condition.SEASON_SPRING, Condition.BIOME_SWAMP, new Condition[]
            {Condition.WEATHER_FOGGY, Condition.WEATHER_RAINING, Condition.WEATHER_CLOUDY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_FOGGY, Condition.WEATHER_SUNNY, Condition.WEATHER_RAINING, Condition.WEATHER_CLOUDY, Condition.WEATHER_FOGGY, Condition.WEATHER_RAINING, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_FOGGY}),
    SPRING_TROPICAL(Condition.SEASON_SPRING, Condition.BIOME_TROPICAL, new Condition[]
            {Condition.WEATHER_RAINING, Condition.WEATHER_STORM, Condition.WEATHER_RAINING, Condition.WEATHER_CLOUDY, Condition.WEATHER_STORM, Condition.WEATHER_RAINING, Condition.WEATHER_RAINING, Condition.WEATHER_SUNNY, Condition.WEATHER_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_CLOUDY}),
    SPRING_WILDERNESS(Condition.SEASON_SPRING, Condition.BIOME_WILDERNESS, new Condition[]
            {Condition.WEATHER_ASHFALL, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_ASHFALL, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_ASHFALL, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_ASHFALL, Condition.WEATHER_SUNNY}),

    SUMMER_ARCTIC(Condition.SEASON_SUMMER, Condition.BIOME_ARCTIC, new Condition[]
            {Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_RAINING, Condition.WEATHER_FOGGY, Condition.WEATHER_SUNNY, Condition.WEATHER_CLOUDY, Condition.WEATHER_STORM, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_STORM}),
    SUMMER_BARRENS(Condition.SEASON_SUMMER, Condition.BIOME_BARRENS, new Condition[]
            {Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_CLOUDY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_STORM, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_STORM, Condition.WEATHER_CLOUDY}),
    SUMMER_CAVE(Condition.SEASON_SUMMER, Condition.BIOME_CAVE, new Condition[]
            {Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED}),
    SUMMER_COSMOS(Condition.SEASON_SUMMER, Condition.BIOME_COSMOS, new Condition[]
            {Condition.WEATHER_COSMOS, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_COSMOS, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY}),
    SUMMER_DESERT(Condition.SEASON_SUMMER, Condition.BIOME_DESERT, new Condition[]
            {Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY}),
    SUMMER_FOREST(Condition.SEASON_SUMMER, Condition.BIOME_FOREST, new Condition[]
            {Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_RAINING, Condition.WEATHER_STORM, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_RAINING}),
    SUMMER_GRASSLAND(Condition.SEASON_SUMMER, Condition.BIOME_GRASSLAND, new Condition[]
            {Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_RAINING, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_CLOUDY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_STORM, Condition.WEATHER_RAINING, Condition.WEATHER_PARTLY_CLOUDY}),
    SUMMER_LAVA_CAVE(Condition.SEASON_SUMMER, Condition.BIOME_LAVA_CAVE, new Condition[]
            {Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED}),
    SUMMER_MOUNTAIN(Condition.SEASON_SUMMER, Condition.BIOME_MOUNTAIN, new Condition[]
            {Condition.WEATHER_RAINING, Condition.WEATHER_CLOUDY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_STORM, Condition.WEATHER_RAINING, Condition.WEATHER_CLOUDY, Condition.WEATHER_FOGGY, Condition.WEATHER_RAINING, Condition.WEATHER_FOGGY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY}),
    SUMMER_SWAMP(Condition.SEASON_SUMMER, Condition.BIOME_SWAMP, new Condition[]
            {Condition.WEATHER_SUNNY, Condition.WEATHER_FOGGY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_FOGGY, Condition.WEATHER_RAINING, Condition.WEATHER_CLOUDY, Condition.WEATHER_RAINING, Condition.WEATHER_CLOUDY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_RAINING}),
    SUMMER_TROPICAL(Condition.SEASON_SUMMER, Condition.BIOME_TROPICAL, new Condition[]
            {Condition.WEATHER_STORM, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_STORM, Condition.WEATHER_RAINING, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_RAINING}),
    SUMMER_WILDERNESS(Condition.SEASON_SUMMER, Condition.BIOME_WILDERNESS, new Condition[]
            {Condition.WEATHER_ASHFALL, Condition.WEATHER_ASHFALL, Condition.WEATHER_ASHFALL, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_ASHFALL, Condition.WEATHER_SUNNY, Condition.WEATHER_ASHFALL, Condition.WEATHER_ASHFALL, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY}),

    AUTUMN_ARCTIC(Condition.SEASON_AUTUMN, Condition.BIOME_ARCTIC, new Condition[]
            {Condition.WEATHER_FOGGY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_CLOUDY, Condition.WEATHER_SNOWING, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SNOWING, Condition.WEATHER_SUNNY, Condition.WEATHER_FOGGY, Condition.WEATHER_FOGGY, Condition.WEATHER_CLOUDY, Condition.WEATHER_SNOWING, Condition.WEATHER_CLOUDY}),
    AUTUMN_BARRENS(Condition.SEASON_AUTUMN, Condition.BIOME_BARRENS, new Condition[]
            {Condition.WEATHER_RAINING, Condition.WEATHER_CLOUDY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_CLOUDY, Condition.WEATHER_STORM, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_CLOUDY, Condition.WEATHER_PARTLY_CLOUDY}),
    AUTUMN_CAVE(Condition.SEASON_AUTUMN, Condition.BIOME_CAVE, new Condition[]
            {Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED}),
    AUTUMN_COSMOS(Condition.SEASON_AUTUMN, Condition.BIOME_COSMOS, new Condition[]
            {Condition.WEATHER_COSMOS, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_COSMOS, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY}),
    AUTUMN_DESERT(Condition.SEASON_AUTUMN, Condition.BIOME_DESERT, new Condition[]
            {Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_RAINING, Condition.WEATHER_SUNNY}),
    AUTUMN_FOREST(Condition.SEASON_AUTUMN, Condition.BIOME_FOREST, new Condition[]
            {Condition.WEATHER_RAINING, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_FOGGY, Condition.WEATHER_RAINING, Condition.WEATHER_FOGGY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_CLOUDY, Condition.WEATHER_RAINING, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_FOGGY, Condition.WEATHER_SUNNY}),
    AUTUMN_GRASSLAND(Condition.SEASON_AUTUMN, Condition.BIOME_GRASSLAND, new Condition[]
            {Condition.WEATHER_FOGGY, Condition.WEATHER_RAINING, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_CLOUDY, Condition.WEATHER_STORM, Condition.WEATHER_SUNNY, Condition.WEATHER_FOGGY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_FOGGY, Condition.WEATHER_SUNNY}),
    AUTUMN_LAVA_CAVE(Condition.SEASON_AUTUMN, Condition.BIOME_LAVA_CAVE, new Condition[]
            {Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED}),
    AUTUMN_MOUNTAIN(Condition.SEASON_AUTUMN, Condition.BIOME_MOUNTAIN, new Condition[]
            {Condition.WEATHER_FOGGY, Condition.WEATHER_SNOWING, Condition.WEATHER_CLOUDY, Condition.WEATHER_SNOWING, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_FOGGY, Condition.WEATHER_STORM, Condition.WEATHER_SNOWING, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_STORM}),
    AUTUMN_SWAMP(Condition.SEASON_AUTUMN, Condition.BIOME_SWAMP, new Condition[]
            {Condition.WEATHER_FOGGY, Condition.WEATHER_FOGGY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_CLOUDY, Condition.WEATHER_RAINING, Condition.WEATHER_FOGGY, Condition.WEATHER_STORM, Condition.WEATHER_FOGGY, Condition.WEATHER_RAINING, Condition.WEATHER_RAINING, Condition.WEATHER_FOGGY, Condition.WEATHER_CLOUDY}),
    AUTUMN_TROPICAL(Condition.SEASON_AUTUMN, Condition.BIOME_TROPICAL, new Condition[]
            {Condition.WEATHER_RAINING, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_STORM, Condition.WEATHER_RAINING, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_RAINING, Condition.WEATHER_STORM, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_STORM}),
    AUTUMN_WILDERNESS(Condition.SEASON_AUTUMN, Condition.BIOME_WILDERNESS, new Condition[]
            {Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_ASHFALL, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_ASHFALL, Condition.WEATHER_ASHFALL, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_ASHFALL, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_ASHFALL}),

    WINTER_ARCTIC(Condition.SEASON_WINTER, Condition.BIOME_ARCTIC, new Condition[]
            {Condition.WEATHER_SNOWING, Condition.WEATHER_SNOWING, Condition.WEATHER_CLOUDY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_SNOWING, Condition.WEATHER_SNOWING, Condition.WEATHER_FOGGY, Condition.WEATHER_SNOWING, Condition.WEATHER_CLOUDY, Condition.WEATHER_SNOWING, Condition.WEATHER_FOGGY}),
    WINTER_BARRENS(Condition.SEASON_WINTER, Condition.BIOME_BARRENS, new Condition[]
            {Condition.WEATHER_FOGGY, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_CLOUDY, Condition.WEATHER_STORM, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_STORM, Condition.WEATHER_CLOUDY, Condition.WEATHER_STORM, Condition.WEATHER_SUNNY}),
    WINTER_CAVE(Condition.SEASON_WINTER, Condition.BIOME_CAVE, new Condition[]
            {Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED}),
    WINTER_COSMOS(Condition.SEASON_WINTER, Condition.BIOME_COSMOS, new Condition[]
            {Condition.WEATHER_COSMOS, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_COSMOS, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY}),
    WINTER_DESERT(Condition.SEASON_WINTER, Condition.BIOME_DESERT, new Condition[]
            {Condition.WEATHER_FOGGY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY, Condition.WEATHER_FOGGY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY}),
    WINTER_FOREST(Condition.SEASON_WINTER, Condition.BIOME_FOREST, new Condition[]
            {Condition.WEATHER_SNOWING, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_FOGGY, Condition.WEATHER_SUNNY, Condition.WEATHER_CLOUDY, Condition.WEATHER_SNOWING, Condition.WEATHER_SNOWING, Condition.WEATHER_CLOUDY, Condition.WEATHER_FOGGY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_SUNNY}),
    WINTER_GRASSLAND(Condition.SEASON_WINTER, Condition.BIOME_GRASSLAND, new Condition[]
            {Condition.WEATHER_SNOWING, Condition.WEATHER_FOGGY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_FOGGY, Condition.WEATHER_SNOWING, Condition.WEATHER_SNOWING, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SUNNY, Condition.WEATHER_SNOWING, Condition.WEATHER_CLOUDY, Condition.WEATHER_PARTLY_CLOUDY}),
    WINTER_LAVA_CAVE(Condition.SEASON_WINTER, Condition.BIOME_LAVA_CAVE, new Condition[]
            {Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED, Condition.WEATHER_COVERED}),
    WINTER_MOUNTAIN(Condition.SEASON_WINTER, Condition.BIOME_MOUNTAIN, new Condition[]
            {Condition.WEATHER_SNOWING, Condition.WEATHER_SNOWING, Condition.WEATHER_STORM, Condition.WEATHER_SNOWING, Condition.WEATHER_CLOUDY, Condition.WEATHER_STORM, Condition.WEATHER_SNOWING, Condition.WEATHER_FOGGY, Condition.WEATHER_SUNNY, Condition.WEATHER_STORM, Condition.WEATHER_STORM, Condition.WEATHER_CLOUDY}),
    WINTER_SWAMP(Condition.SEASON_WINTER, Condition.BIOME_SWAMP, new Condition[]
            {Condition.WEATHER_SNOWING, Condition.WEATHER_FOGGY, Condition.WEATHER_RAINING, Condition.WEATHER_FOGGY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_SNOWING, Condition.WEATHER_SUNNY, Condition.WEATHER_FOGGY, Condition.WEATHER_SNOWING, Condition.WEATHER_RAINING, Condition.WEATHER_SNOWING, Condition.WEATHER_FOGGY}),
    WINTER_TROPICAL(Condition.SEASON_WINTER, Condition.BIOME_TROPICAL, new Condition[]
            {Condition.WEATHER_RAINING, Condition.WEATHER_CLOUDY, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_RAINING, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_RAINING, Condition.WEATHER_CLOUDY, Condition.WEATHER_STORM, Condition.WEATHER_RAINING, Condition.WEATHER_PARTLY_CLOUDY, Condition.WEATHER_STORM, Condition.WEATHER_RAINING}),
    WINTER_WILDERNESS(Condition.SEASON_WINTER, Condition.BIOME_WILDERNESS, new Condition[]
            {Condition.WEATHER_STORM, Condition.WEATHER_SUNNY, Condition.WEATHER_ASHFALL, Condition.WEATHER_ASHFALL, Condition.WEATHER_SUNNY, Condition.WEATHER_STORM, Condition.WEATHER_ASHFALL, Condition.WEATHER_ASHFALL, Condition.WEATHER_SUNNY, Condition.WEATHER_STORM, Condition.WEATHER_STORM, Condition.WEATHER_ASHFALL}),

    ;

    @Getter
    final Condition seasonCondition;
    @Getter
    final Condition biomeCondition;
    @Getter
    final Condition[] forecastArray;

    WeatherForecast(Condition seasonCondition, Condition biomeCondition, Condition[] forecastArray)
    {
        this.seasonCondition = seasonCondition;
        this.biomeCondition = biomeCondition;
        this.forecastArray = forecastArray;
    }
}
